#!/data/data/com.termux/files/usr/bin/bash
echo "[🔐] EchoNull Arsenal Launcher"
echo "----------------------------------"
echo "[🔴] Red Team Tools:"
echo " - sqlmap, nikto, hydra, nmap, metasploit"
echo " - aircrack-ng, ettercap, john, wpscan, burpsuite"
echo " - enum4linux, recon-ng, dnsenum, hping3, netcat"
echo ""
echo "[🔵] Blue Team Tools:"
echo " - clamav, lynis, rkhunter, net-tools, ufw"
echo " - chkrootkit, auditd, fail2ban, tripwire, logwatch"
echo " - sysstat, iptables, snort"
echo ""
echo "[🧠] All tools are now available in your Termux environment."
